name: Sign Release Files

on:
  release:
    types: [published]

jobs:
  sign-release:
    runs-on: windows-latest
    name: Sign release files with Trusted Signing
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download latest release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create directory for assets
          mkdir release-files
          
          # Download exe, dll, and msi files
          gh release download --pattern "*.exe" --pattern "*.dll" --pattern "*.msi" --dir release-files

      - name: Sign files with Trusted Signing
        uses: azure/trusted-signing-action@v0
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: https://eus.codesigning.azure.net/
          trusted-signing-account-name: your-account-name
          certificate-profile-name: your-profile-name
          files-folder: ${{ github.workspace }}/release-files
          files-folder-filter: exe,dll,msi
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256

      - name: Upload signed files back to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest release tag
          $latest_tag = gh release list -L 1 --json tagName --jq '.[0].tagName'
          
          # Upload all signed files back to the release
          Get-ChildItem release-files/*.exe, release-files/*.dll, release-files/*.msi | ForEach-Object {
              gh release upload $latest_tag $_.FullName --clobber
          }
